name = "finntrack-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
# routes = [
#   { pattern = "api.finntracker.org/*", zone_name = "finntracker.org" }
# ]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "RACE_STATE"
class_name = "RaceStateDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RaceStateDO"]

[[r2_buckets]]
binding = "RACES"
bucket_name = "races"

[vars]
CORS_ORIGIN = "*"
